### ISSUE TITLE
Schema du faisceau

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TiboLGH/solextronic#9]
```
+ carte d'adaptation analogique


```

Original issue reported on code.google.com by `thibault...@gmail.com` on 18 Mar 2014 at 9:23

**Comment by TiboLGH** [comment]
Finalement, pas de carte d'adaptation analogique, on fait tout sur la carte principale.

**Comment by TiboLGH** [comment]
commit c8f4fc2ebacf81f8e0f9d55c82d7b0f48d196261
